<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-WebApplication4-e188cca0-65f3-48eb-a751-310abff5e5de</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\bootstrap\**" />
    <Content Remove="wwwroot\bootstrap\**" />
    <EmbeddedResource Remove="wwwroot\bootstrap\**" />
    <None Remove="wwwroot\bootstrap\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.min.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-grid.rtl.min.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.min.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-reboot.rtl.min.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.min.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap-utilities.rtl.min.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.min.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.css.map" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.min.css" />
    <Content Remove="C:\Users\Олег\.nuget\packages\bootstrap\5.3.3\contentFiles\any\any\wwwroot\css\bootstrap.rtl.min.css.map" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="bootstrap" Version="5.3.3" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\004-min.jpg" />
    <None Include="wwwroot\images\2150695899.jpg" />
    <None Include="wwwroot\images\2150695943.jpg" />
    <None Include="wwwroot\images\8618455.png" />
    <None Include="wwwroot\images\default-image.jpg" />
    <None Include="wwwroot\images\empty-flat-interrior-with-elements-decoration.jpg" />
    <None Include="wwwroot\images\loft-authentic-dining-room-interior-design-with-picture-frame8-min.jpg" />
    <None Include="wwwroot\images\modern-entryway-with-furniture-h3.jpg" />
    <None Include="wwwroot\images\modern-luxury-authentic-dining-room-interior-design-with-picture-frame_53876-128701.jpg" />
    <None Include="wwwroot\images\modern-styled-entryway_23-215069.jpg" />
    <None Include="wwwroot\images\modern-styled-entryway_23-2150695941.jpg" />
    <None Include="wwwroot\images\workspace-desk-with-plant-lamp_23-2148592288.jpg" />
  </ItemGroup>

</Project>
